# Generated by Django 5.0.2 on 2024-02-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20, verbose_name='Número de registro (CPF/CNPJ)')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('farm_name', models.CharField(max_length=100, verbose_name='Nome da fazenda')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área total')),
                ('arable_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área agriculturável')),
                ('vegetation_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área de vegetação')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SO', 'Soja'), ('MI', 'Milho'), ('AL', 'Algodão'), ('CA', 'Café'), ('CN', 'Cana de Açúcar')], max_length=2, verbose_name='Nome')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='producer.producer', verbose_name='Produtor')),
            ],
        ),
    ]
