version: "1"

services:

  db:
    build:
      dockerfile: db/Dockerfile
    image: postgres:alpine
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
